[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
upload_port = /dev/cu.usbmodem1113401
monitor_port = /dev/cu.usbmodem1113401

lib_deps =
    sui77/rc-switch @ ^2.6.4
